### ISSUE TITLE
Can't change settings on RootHide&Serotonin

### ISSUE THREAD

**Issue by jrapf32** [ryannair05/Cask-3#3]

**Comment by st4rburn** [comment]
I’ll elaborate; basically the tweak has to be patched by the RootHide patcher (this causes no issues for most tweaks, also may not be the problem here), and then when installed, it looks like you can change the settings at first, but when you change anything, as soon as you go up a menu level and then back in, the change reverts to the default. Cylinder Remade appears to work fine so it could be a difference in how settings work between the two tweaks if there are similarities?

**Comment by st4rburn** [comment]
Update: it looks like the preference file isn’t being created or read from (assuming it is `/var/mobile/Library/Preferences/com.ryannair05.cask3.plist`)
The file wasn’t there when I looked to begin with, and after having a shot at manually creating it with different settings and respringing, there was no change

**Comment by jrapf32** [comment]
ok

**Comment by Oxtie** [comment]
Yep,.. Doesn't work on roothide serotonin 🤔 

Seems like the project has been abandoned 🫤

**Comment by ryannair05** [comment]
> Seems like the project has been abandoned 🫤

Not abandoned, I'll update the tweak to fix this issue when I have the time to do so

**Comment by ryannair05** [comment]
Fixed in Version 1.0.3!
